version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  stops-service:
    build: ./bus_stops_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./bus_stops_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  routes-service:
    build: ./routes_service
    command: uvicorn routes_service:app --host 0.0.0.0 --port 8001
    volumes:
      - ./routes_service:/app
    ports:
      - "8001:8001"


volumes:
  postgres_data:
