version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  stops-service:
    hostname: stops-service
    build: ./bus_stops_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./bus_stops_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  routes-service:
    build: ./routes_service
    command: uvicorn routes_service:app --host 0.0.0.0 --port 8001
    volumes:
      - ./routes_service:/app
    ports:
      - "8001:8001"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  
  keycloak:
    container_name: keycloakapp
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
      KEYCLOAK_ADMIN: admin1
      KEYCLOAK_ADMIN_PASSWORD: admin1
    command:
      - start-dev
    
  server:
    build:
      context: /main
      dockerfile: Dockerfile
    ports:
      - 5051:5051
  

volumes:
  postgres_data:
