name: CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Micros_Bus_Schedule\bus_stops_service\requirements.txt

    - name: Test
      run: |
        pytest tests/

    - name: Build Docker image
      run: |
        docker build -t my_fastapi_app .
